// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCySMjCSGmPJKVEcsYn6_RFryJCNbrrXIg',
    appId: '1:1085138930648:web:7c93f6f9b06aeeb2a480ad',
    messagingSenderId: '1085138930648',
    projectId: 'madiyar-nexus-01',
    authDomain: 'madiyar-nexus-01.firebaseapp.com',
    storageBucket: 'madiyar-nexus-01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAp526FozsFSrQeM1baPsKXWVqG3qxPa0',
    appId: '1:1085138930648:android:059e28323a48b192a480ad',
    messagingSenderId: '1085138930648',
    projectId: 'madiyar-nexus-01',
    storageBucket: 'madiyar-nexus-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA96ls1KWsu8AxVanTnmK_CINXBf-tazts',
    appId: '1:1085138930648:ios:6a5a74008b961ffda480ad',
    messagingSenderId: '1085138930648',
    projectId: 'madiyar-nexus-01',
    storageBucket: 'madiyar-nexus-01.firebasestorage.app',
    iosBundleId: 'com.madiyar.nexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA96ls1KWsu8AxVanTnmK_CINXBf-tazts',
    appId: '1:1085138930648:ios:6a5a74008b961ffda480ad',
    messagingSenderId: '1085138930648',
    projectId: 'madiyar-nexus-01',
    storageBucket: 'madiyar-nexus-01.firebasestorage.app',
    iosBundleId: 'com.madiyar.nexus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwzL_KlxVj7KAIHAroeRgXnPm3tkCYkyo',
    appId: '1:52810814573:web:b1c4d627a9fc32806b9b64',
    messagingSenderId: '52810814573',
    projectId: 'madibook-e96e0',
    authDomain: 'madibook-e96e0.firebaseapp.com',
    storageBucket: 'madibook-e96e0.firebasestorage.app',
    measurementId: 'G-T178E2M8QJ',
  );

}