// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwzL_KlxVj7KAIHAroeRgXnPm3tkCYkyo',
    appId: '1:52810814573:web:7decf4a424e34f096b9b64',
    messagingSenderId: '52810814573',
    projectId: 'madibook-e96e0',
    authDomain: 'madibook-e96e0.firebaseapp.com',
    storageBucket: 'madibook-e96e0.firebasestorage.app',
    measurementId: 'G-5Y2F689VHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjumgPG1LUhGx4hI_f9x8hYHlK5JVNHcs',
    appId: '1:52810814573:android:609701709e4ee27c6b9b64',
    messagingSenderId: '52810814573',
    projectId: 'madibook-e96e0',
    storageBucket: 'madibook-e96e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8QsbWWm5N_uBt10TXoIuWGBA12g15ANQ',
    appId: '1:52810814573:ios:aa095083e0d5e6f56b9b64',
    messagingSenderId: '52810814573',
    projectId: 'madibook-e96e0',
    storageBucket: 'madibook-e96e0.firebasestorage.app',
    iosBundleId: 'com.example.madibook',
  );
}
